import type { ParticleEmitterConfig, ParticlePresetId } from '@/types/particle';
import { DEFAULT_PARTICLE_CONFIG } from '@/types/particle';

export interface ParticlePresetMeta {
  id: ParticlePresetId;
  label: string;
  description: string;
  config: Partial<ParticleEmitterConfig>;
}

export const PARTICLE_PRESETS: ParticlePresetMeta[] = [
  {
    id: 'smoke',
    label: '浓烟',
    description: '灰白烟雾，缓慢上升并扩散，适合烟囱、火灾',
    config: {
      maxParticles: 1600,
      emissionRate: 130,
      lifetimeMin: 3,
      lifetimeMax: 6,
      sizeStart: 0.8,
      sizeEnd: 4.2,
      speedMin: 0.3,
      speedMax: 0.9,
      spread: 0.8,
      direction: [0, 1, 0],
      emitShape: 'sphere',
      emitSize: [0.8, 0.5, 0.8],
      colorStart: '#d0d0d0',
      colorEnd: '#3a3a3a',
      opacityStart: 0.65,
      opacityEnd: 0,
      gravity: [0, 0.25, 0],
      turbulence: 2.0,
      rotationSpeed: 0.6,
      blendMode: 'normal',
      texture: 'smoke',
      showHelper: false,
    },
  },
  {
    id: 'steam',
    label: '蒸汽',
    description: '白色半透明蒸汽，快速上升消散',
    config: {
      maxParticles: 1400,
      emissionRate: 140,
      lifetimeMin: 1.8,
      lifetimeMax: 3.5,
      sizeStart: 0.65,
      sizeEnd: 3.2,
      speedMin: 1.0,
      speedMax: 2.0,
      spread: 0.55,
      direction: [0, 1, 0],
      emitShape: 'sphere',
      emitSize: [0.9, 0.5, 0.9],
      colorStart: '#ffffff',
      colorEnd: '#aaaaaa',
      opacityStart: 0.7,
      opacityEnd: 0,
      gravity: [0, 0.55, 0],
      turbulence: 1.4,
      rotationSpeed: 1.4,
      blendMode: 'normal',
      texture: 'smoke',
    },
  },
  {
    id: 'fire',
    label: '火焰',
    description: '橙红火焰，加法混合，适合燃烧效果',
    config: {
      maxParticles: 800,
      emissionRate: 200,
      lifetimeMin: 0.35,
      lifetimeMax: 1.0,
      sizeStart: 0.75,
      sizeEnd: 0.12,
      speedMin: 1.0,
      speedMax: 2.8,
      spread: 0.55,
      direction: [0, 1, 0],
      emitShape: 'sphere',
      emitSize: [0.55, 0.15, 0.55],
      colorStart: '#ffcc33',
      colorEnd: '#ff3300',
      opacityStart: 1,
      opacityEnd: 0,
      gravity: [0, 0.6, 0],
      turbulence: 2.2,
      rotationSpeed: 3.5,
      blendMode: 'additive',
      texture: 'soft',
    },
  },
  {
    id: 'sparks',
    label: '火花',
    description: '明亮火花飞溅，受重力下落',
    config: {
      maxParticles: 600,
      emissionRate: 180,
      lifetimeMin: 0.35,
      lifetimeMax: 1.2,
      sizeStart: 0.32,
      sizeEnd: 0.04,
      speedMin: 3.5,
      speedMax: 9,
      spread: 1.4,
      direction: [0, 1, 0],
      emitShape: 'point',
      emitSize: [0.15, 0.15, 0.15],
      colorStart: '#fff8aa',
      colorEnd: '#ff5500',
      opacityStart: 1,
      opacityEnd: 0,
      gravity: [0, -6, 0],
      turbulence: 0.4,
      rotationSpeed: 6,
      blendMode: 'additive',
      texture: 'spark',
    },
  },
  {
    id: 'dust',
    label: '扬尘',
    description: '棕色粉尘缓慢飘散',
    config: {
      maxParticles: 700,
      emissionRate: 55,
      lifetimeMin: 4,
      lifetimeMax: 8,
      sizeStart: 0.15,
      sizeEnd: 0.35,
      speedMin: 0.15,
      speedMax: 0.55,
      spread: 1.6,
      direction: [0, 0.4, 0],
      emitShape: 'box',
      emitSize: [3, 0.3, 3],
      colorStart: '#a08060',
      colorEnd: '#5a4a35',
      opacityStart: 0.75,
      opacityEnd: 0,
      gravity: [0, -0.08, 0],
      turbulence: 1.0,
      rotationSpeed: 0.4,
      blendMode: 'normal',
      texture: 'soft',
    },
  },
  {
    id: 'magic',
    label: '魔法能量',
    description: '紫色能量粒子环绕飘散',
    config: {
      maxParticles: 900,
      emissionRate: 150,
      lifetimeMin: 1,
      lifetimeMax: 2.8,
      sizeStart: 0.35,
      sizeEnd: 0.08,
      speedMin: 0.7,
      speedMax: 2.0,
      spread: 2.8,
      direction: [0, 1, 0],
      emitShape: 'sphere',
      emitSize: [1.0, 1.0, 1.0],
      colorStart: '#ee88ff',
      colorEnd: '#4400cc',
      opacityStart: 1,
      opacityEnd: 0,
      gravity: [0, 0.15, 0],
      turbulence: 2.8,
      rotationSpeed: 5,
      blendMode: 'additive',
      texture: 'spark',
    },
  },
  {
    id: 'rain',
    label: '降雨',
    description: '细密雨丝从上往下，适合天气效果（默认生成在 y=14）',
    config: {
      maxParticles: 8000,
      emissionRate: 2200,
      lifetimeMin: 0.55,
      lifetimeMax: 1.0,
      sizeStart: 0.07,
      sizeEnd: 0.05,
      speedMin: 11,
      speedMax: 17,
      spread: 0.04,
      direction: [0, -1, 0],
      emitShape: 'box',
      emitSize: [32, 1, 32],
      colorStart: '#d0dae8',
      colorEnd: '#9aacbe',
      opacityStart: 0.38,
      opacityEnd: 0.18,
      gravity: [0, -3, 0],
      turbulence: 0.02,
      rotationSpeed: 0,
      blendMode: 'normal',
      texture: 'soft',
      showHelper: false,
    },
  },
  {
    id: 'snow',
    label: '飘雪',
    description: '白色雪花缓慢飘落，带轻微横风（默认生成在 y=12）',
    config: {
      maxParticles: 2500,
      emissionRate: 200,
      lifetimeMin: 7,
      lifetimeMax: 14,
      sizeStart: 0.45,
      sizeEnd: 0.28,
      speedMin: 0.4,
      speedMax: 1.0,
      spread: 0.25,
      direction: [0, -1, 0],
      emitShape: 'box',
      emitSize: [24, 1, 24],
      colorStart: '#ffffff',
      colorEnd: '#e8f4ff',
      opacityStart: 1,
      opacityEnd: 0.45,
      gravity: [0.12, -0.9, 0.06],
      turbulence: 0.6,
      rotationSpeed: 1.5,
      blendMode: 'normal',
      texture: 'soft',
      showHelper: false,
    },
  },
  {
    id: 'explosion',
    label: '爆炸',
    description: '瞬间爆发的火焰与烟尘，适合撞击、爆炸特效',
    config: {
      maxParticles: 900,
      emissionRate: 400,
      lifetimeMin: 0.2,
      lifetimeMax: 0.9,
      sizeStart: 0.9,
      sizeEnd: 0.15,
      speedMin: 4,
      speedMax: 11,
      spread: 2.8,
      direction: [0, 1, 0],
      emitShape: 'sphere',
      emitSize: [0.6, 0.6, 0.6],
      colorStart: '#ffee66',
      colorEnd: '#ff2200',
      opacityStart: 1,
      opacityEnd: 0,
      gravity: [0, -3, 0],
      turbulence: 2.5,
      rotationSpeed: 4,
      blendMode: 'additive',
      texture: 'spark',
    },
  },
  {
    id: 'mist',
    label: '雾气',
    description: '贴地慢速流动的薄雾，适合清晨、湖面氛围',
    config: {
      maxParticles: 1800,
      emissionRate: 100,
      lifetimeMin: 6,
      lifetimeMax: 12,
      sizeStart: 1.5,
      sizeEnd: 4.5,
      speedMin: 0.08,
      speedMax: 0.25,
      spread: 1.8,
      direction: [0, 0.15, 0],
      emitShape: 'box',
      emitSize: [16, 0.4, 16],
      colorStart: '#e8eef5',
      colorEnd: '#b8c8d8',
      opacityStart: 0.45,
      opacityEnd: 0,
      gravity: [0.02, 0.05, 0.01],
      turbulence: 0.9,
      rotationSpeed: 0.2,
      blendMode: 'normal',
      texture: 'smoke',
      showHelper: false,
    },
  },
  {
    id: 'bubbles',
    label: '气泡',
    description: '透明气泡缓慢上升，适合水池、肥皂泡',
    config: {
      maxParticles: 500,
      emissionRate: 70,
      lifetimeMin: 3,
      lifetimeMax: 7,
      sizeStart: 0.25,
      sizeEnd: 0.55,
      speedMin: 0.4,
      speedMax: 1.2,
      spread: 0.6,
      direction: [0, 1, 0],
      emitShape: 'sphere',
      emitSize: [1.2, 0.4, 1.2],
      colorStart: '#e8ffff',
      colorEnd: '#88ccff',
      opacityStart: 0.55,
      opacityEnd: 0.05,
      gravity: [0, 0.35, 0],
      turbulence: 0.5,
      rotationSpeed: 0.6,
      blendMode: 'normal',
      texture: 'soft',
    },
  },
  {
    id: 'embers',
    label: '余烬',
    description: '暗红火星缓缓飘升，适合篝火、熔炉余温',
    config: {
      maxParticles: 700,
      emissionRate: 120,
      lifetimeMin: 1.5,
      lifetimeMax: 4,
      sizeStart: 0.2,
      sizeEnd: 0.05,
      speedMin: 0.5,
      speedMax: 1.8,
      spread: 1.0,
      direction: [0, 1, 0],
      emitShape: 'box',
      emitSize: [1.2, 0.2, 1.2],
      colorStart: '#ffaa44',
      colorEnd: '#cc2200',
      opacityStart: 1,
      opacityEnd: 0,
      gravity: [0, 0.25, 0],
      turbulence: 1.5,
      rotationSpeed: 3,
      blendMode: 'additive',
      texture: 'spark',
    },
  },
  {
    id: 'confetti',
    label: '彩纸',
    description: '彩色碎屑从空中飘落，适合庆典、舞台效果',
    config: {
      maxParticles: 2000,
      emissionRate: 180,
      lifetimeMin: 5,
      lifetimeMax: 10,
      sizeStart: 0.28,
      sizeEnd: 0.18,
      speedMin: 0.5,
      speedMax: 1.2,
      spread: 0.4,
      direction: [0, -1, 0],
      emitShape: 'box',
      emitSize: [20, 1, 20],
      colorStart: '#ff66aa',
      colorEnd: '#ffcc33',
      opacityStart: 1,
      opacityEnd: 0.5,
      gravity: [0.08, -1.2, 0.04],
      turbulence: 1.2,
      rotationSpeed: 4,
      blendMode: 'normal',
      texture: 'soft',
      showHelper: false,
    },
  },
];

export function getPresetConfig(presetId: ParticlePresetId): ParticleEmitterConfig {
  const preset = PARTICLE_PRESETS.find((p) => p.id === presetId);
  if (!preset || presetId === 'custom') {
    return { ...DEFAULT_PARTICLE_CONFIG };
  }
  return { ...DEFAULT_PARTICLE_CONFIG, ...preset.config, preset: presetId };
}

export function mergeParticleConfig(
  base: ParticleEmitterConfig,
  updates: Partial<ParticleEmitterConfig>
): ParticleEmitterConfig {
  return { ...base, ...updates };
}
